"""Regression coverage for generated objdiff decomp.me scratch metadata."""

import io
import json
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import mock_open, patch

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.project import Object, ProjectConfig, generate_objdiff_config


class ProjectScratchTests(unittest.TestCase):
    def generate(self, version, *, object_override=False, module=False):
        config = ProjectConfig()
        config.version = "TEST"
        options = {"mw_version": version} if object_override else {}
        config.libs = [{
            "mw_version": "GC/1.3.2" if object_override else version,
            "cflags": ["-O4,p", "-i include"],
            "objects": [Object(True, "runtime.c", **options)],
        }]
        unit = {
            "name": "runtime.c",
            "object": "build/TEST/orig/runtime.o",
            "autogenerated": False,
        }
        build_config = {
            "name": "main",
            "units": [] if module else [unit],
            "modules": [{"name": "runtime", "units": [unit]}] if module else [],
        }
        output = mock_open()
        warnings = io.StringIO()
        # Exercise the real generator without reading retail inputs or writing
        # the live workspace's objdiff.json.
        with patch("pathlib.Path.exists", return_value=True), \
                patch("builtins.open", output), redirect_stdout(warnings):
            generate_objdiff_config(config, build_config)
        output.assert_called_once_with("objdiff.json", "w", encoding="utf-8")
        generated = json.loads("".join(call.args[0] for call in output().write.call_args_list))
        return generated["units"][0], warnings.getvalue()

    def test_gc13_generates_exact_backend_for_library_and_object_options(self):
        # GC/1.3/mwcceppc.exe -version: Version 2.4.2 build 53.
        # decompme/decomp.me backend/coreapp/compilers.py registers mwcc_242_53.
        for object_override in (False, True):
            for module in (False, True):
                with self.subTest(object_override=object_override, module=module):
                    unit, warnings = self.generate(
                        "GC/1.3", object_override=object_override, module=module
                    )
                    self.assertEqual(warnings, "")
                    self.assertEqual(unit["scratch"], {
                        "platform": "gc_wii",
                        "compiler": "mwcc_242_53",
                        "c_flags": "-lang=c -O4,p",
                        "ctx_path": "build/TEST/src/runtime.ctx",
                        "build_ctx": True,
                    })
                    self.assertTrue(unit["complete"])

    def test_gc132_keeps_distinct_backend(self):
        unit, warnings = self.generate("GC/1.3.2")
        self.assertEqual(warnings, "")
        self.assertEqual(unit["scratch"]["compiler"], "mwcc_242_81")

    def test_unsupported_compiler_warns_without_fallback(self):
        unit, warnings = self.generate("GC/unsupported", object_override=True)
        self.assertEqual(warnings, "Missing scratch compiler mapping for GC/unsupported\n")
        self.assertNotIn("scratch", unit)
        self.assertEqual(unit["base_path"], "build/TEST/src/runtime.o")
        self.assertTrue(unit["complete"])


if __name__ == "__main__":
    unittest.main()
