import subprocess
import tempfile
import unittest
from pathlib import Path

from tools.promote_recovered_c import (
    PromotionError,
    audit_promotion,
    branch_errors,
    create_promotion,
    plan_promotion,
    source_ai_markers,
)


def run(cwd: Path, *args: str) -> str:
    result = subprocess.run(
        args,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


class PromotionTests(unittest.TestCase):
    def fixture(self) -> tuple[tempfile.TemporaryDirectory[str], Path, str]:
        temporary = tempfile.TemporaryDirectory()
        root = Path(temporary.name) / "repo"
        root.mkdir()
        run(root, "git", "init", "-q", "-b", "main")
        run(root, "git", "config", "user.email", "test@example.com")
        run(root, "git", "config", "user.name", "Test")
        (root / "src/game").mkdir(parents=True)
        (root / "tools").mkdir()
        (root / "src/game/example.c").write_text(
            "int Example(void)\n{\n    return 0;\n}\n",
            encoding="utf-8",
        )
        (root / "README.md").write_text("Human project\n", encoding="utf-8")
        run(root, "git", "add", ".")
        run(root, "git", "commit", "-qm", "Initial source")
        base = run(root, "git", "rev-parse", "HEAD")
        run(root, "git", "checkout", "-qb", "agent/recovery-lab")
        (root / "src/game/example.c").write_text(
            "int Example(void)\n{\n    return 1;\n}\n",
            encoding="utf-8",
        )
        (root / "tools/lab.py").write_text("print('tooling')\n", encoding="utf-8")
        run(root, "git", "add", ".")
        run(root, "git", "commit", "-qm", "Recover example with internal tooling")
        return temporary, root, base

    def test_plan_selects_only_recovered_c(self):
        temporary, root, base = self.fixture()
        try:
            value = plan_promotion(
                root,
                base_ref=base,
                source_ref="HEAD",
                allow_unverified=True,
            )
            self.assertEqual(
                [item["path"] for item in value["files"]],
                ["src/game/example.c"],
            )
        finally:
            temporary.cleanup()

    def test_headers_are_not_automatically_promotable(self):
        temporary, root, base = self.fixture()
        try:
            with self.assertRaisesRegex(PromotionError, "src/.*\\.c"):
                plan_promotion(
                    root,
                    base_ref=base,
                    source_ref="HEAD",
                    paths=["include/game/example.h"],
                    allow_unverified=True,
                )
        finally:
            temporary.cleanup()

    def test_ai_attribution_in_comment_is_rejected(self):
        self.assertTrue(
            source_ai_markers("int f(void) { return 0; } // generated by Claude\n")
        )
        temporary, root, base = self.fixture()
        try:
            (root / "src/game/example.c").write_text(
                "// AI-generated recovery\nint Example(void) { return 1; }\n",
                encoding="utf-8",
            )
            run(root, "git", "add", "src/game/example.c")
            run(root, "git", "commit", "-qm", "Update source")
            with self.assertRaisesRegex(PromotionError, "AI-generated"):
                plan_promotion(
                    root,
                    base_ref=base,
                    source_ref="HEAD",
                    allow_unverified=True,
                )
        finally:
            temporary.cleanup()

    def test_create_starts_from_main_and_copies_exact_blob(self):
        temporary, root, base = self.fixture()
        promotion = Path(temporary.name) / "promotion"
        try:
            source_commit = run(root, "git", "rev-parse", "HEAD")
            hook = root / ".git/hooks/pre-commit"
            hook.write_text("#!/bin/sh\nexit 99\n", encoding="utf-8")
            hook.chmod(0o755)
            result = create_promotion(
                root,
                base_ref=base,
                source_ref=source_commit,
                branch="recovery/example",
                worktree=promotion,
                title="Recover example processing",
                paths=["src/game/example.c"],
                owner=None,
                allow_unverified=True,
            )
            changed = run(
                promotion,
                "git",
                "diff",
                "--name-only",
                f"{base}...HEAD",
            ).splitlines()
            self.assertEqual(changed, ["src/game/example.c"])
            self.assertFalse((promotion / "tools/lab.py").exists())
            self.assertTrue(result["promotion"]["audit"]["clean_human_promotion"])
            source_blob = run(root, "git", "rev-parse", f"{source_commit}:src/game/example.c")
            promoted_blob = run(promotion, "git", "rev-parse", "HEAD:src/game/example.c")
            self.assertEqual(source_blob, promoted_blob)
            self.assertEqual(run(promotion, "git", "rev-parse", "HEAD^"), base)
            message = run(promotion, "git", "log", "-1", "--format=%B")
            self.assertEqual(message, "Recover example processing")
        finally:
            subprocess.run(
                ["git", "worktree", "remove", "--force", str(promotion)],
                cwd=root,
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            temporary.cleanup()

    def test_branch_names_with_ai_words_are_refused(self):
        for branch in (
            "recovery/agent-fix",
            "recovery/ai-fix",
            "recovery/agent_fix",
            "recovery/fix-by-ai",
            "recovery/claude-frand",
        ):
            self.assertTrue(
                any("AI/agent" in error for error in branch_errors(branch)),
                branch,
            )
        # "ai"/"agent" embedded inside larger words are not attribution.
        self.assertEqual(branch_errors("recovery/maintain-repair"), [])
        self.assertEqual(branch_errors("recovery/example"), [])

    def test_audit_rejects_non_c_and_ai_commit_messages(self):
        temporary, root, base = self.fixture()
        try:
            run(root, "git", "checkout", "-qb", "recovery/bad", base)
            (root / "README.md").write_text("changed\n", encoding="utf-8")
            run(root, "git", "add", "README.md")
            run(root, "git", "commit", "-qm", "AI assisted cleanup")
            result = audit_promotion(
                root,
                base_ref=base,
                head_ref="HEAD",
            )
            self.assertFalse(result["clean_human_promotion"])
            self.assertTrue(any("README.md" in error for error in result["errors"]))
            self.assertTrue(any("attribution" in error for error in result["errors"]))
        finally:
            temporary.cleanup()


if __name__ == "__main__":
    unittest.main()
