#ifndef GAME_SAVELOAD_LAYOUT_H
#define GAME_SAVELOAD_LAYOUT_H

#include "dolphin.h"
#include "game/gamework.h"

#define SAVE_ROUNDUP(value, alignment) (((value) + ((alignment) - 1)) & ~((alignment) - 1))

#define SAVE_SECTOR_SIZE 8192

#define SAVE_COMMENT_OFS 0
#define SAVE_BANNER_OFS (SAVE_COMMENT_OFS + CARD_COMMENT_SIZE)
#define SAVE_COMMENT_DATE_OFS (CARD_COMMENT_SIZE / 2)

#define SAVE_BANNER_TLUT_OFS (SAVE_BANNER_OFS + (CARD_BANNER_WIDTH * CARD_BANNER_HEIGHT))
#define SAVE_ICON_OFS (SAVE_BANNER_TLUT_OFS + 512)
#define SAVE_ICON_TLUT_OFS (SAVE_ICON_OFS + (CARD_ICON_WIDTH * CARD_ICON_HEIGHT * 4))
#define SAVE_ICONBANNER_CHECKSUM_OFS (SAVE_ICON_TLUT_OFS + 512)
#define SAVE_ICONBANNER_SIZE SAVE_ICONBANNER_CHECKSUM_OFS

#define SAVE_BOX_SIZE \
    (SAVE_ROUNDUP(sizeof(GW_COMMON) + sizeof(GW_SYSTEM) + (GW_PLAYER_MAX * sizeof(GW_PLAYER)), 4) + 2)

#define SAVE_BOX_DATA_OFS (SAVE_ICONBANNER_CHECKSUM_OFS + 2)
#define SAVE_BOX_OFS(boxNo) (SAVE_BOX_DATA_OFS + (SAVE_BOX_SIZE * (boxNo)))

#define SAVE_BOX_MAX 3
#define SAVE_BOXNO_BACKUP SAVE_BOX_MAX

#define SAVE_BOXBACKUP_DATA_OFS SAVE_ROUNDUP(SAVE_BOX_OFS(SAVE_BOX_MAX), SAVE_SECTOR_SIZE)
#define SAVE_BOXBACKUP_OFS(boxNo) (SAVE_BOXBACKUP_DATA_OFS + (SAVE_BOX_SIZE * (boxNo)))

#define SAVE_BUF_SIZE SAVE_ROUNDUP(SAVE_BOXBACKUP_OFS(SAVE_BOX_MAX), SAVE_SECTOR_SIZE)

#endif
