#!/usr/bin/env python3
"""Prepare, freeze, score, archive, and audit blind source-recovery trials.

The benchmark separates four questions that are often conflated:

* Did the candidate reproduce the target assembly?
* Did it resemble the retained source after the blind phase ended?
* Does it look like organic, maintainable C rather than match-shaped scaffolding?
* Is the trial independently replayable from preserved artifacts?

Only the Python standard library is required. Retail or proprietary compiler
steps remain external: callers may supply target/candidate assembly generated by
objdiff, DTK, Metrowerks, Clang, or another controlled toolchain.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.recovery_data import Function, RecoveryError, function_text, parse_functions

SCHEMA_VERSION = 1
DEFAULT_MANIFEST = Path("benchmarks/blind_recovery/manifest.json")
DEFAULT_RUN_ROOT = Path("build/blind-recovery")
REPRODUCIBLE = "reproducible"
LEGACY = "legacy-reported"
CASE_STATUSES = {REPRODUCIBLE, LEGACY}


class BenchmarkError(ValueError):
    pass


@dataclass(frozen=True)
class Finding:
    id: str
    category: str
    severity: int
    count: int
    message: str
    lines: tuple[int, ...]
    confidence: str = "medium"

    @property
    def deduction(self) -> int:
        return min(self.severity * self.count, self.severity * 3)


@dataclass(frozen=True)
class Organicity:
    score: int
    rating: str
    findings: tuple[Finding, ...]
    category_deductions: Mapping[str, int]
    human_review_required: bool

    def as_dict(self) -> dict[str, Any]:
        return {
            "score": self.score,
            "rating": self.rating,
            "findings": [
                asdict(item) | {"deduction": item.deduction}
                for item in self.findings
            ],
            "category_deductions": dict(self.category_deductions),
            "human_review_required": self.human_review_required,
        }


@dataclass(frozen=True)
class AssemblyComparison:
    status: str
    exact: bool | None
    similarity: float | None
    target_lines: int
    candidate_lines: int

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SourceComparison:
    exact_tokens: bool
    token_similarity: float
    reference_tokens: int
    candidate_tokens: int

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise BenchmarkError(f"missing JSON file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise BenchmarkError(
            f"invalid JSON {path}:{exc.lineno}:{exc.colno}: {exc.msg}"
        ) from exc
    if not isinstance(value, dict):
        raise BenchmarkError(f"{path}: expected a JSON object")
    return value


def _write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as handle:
        json.dump(value, handle, indent=2, sort_keys=True)
        handle.write("\n")
        temporary = Path(handle.name)
    os.replace(temporary, path)


def _run(root: Path, *args: str, allow_failure: bool = False) -> str:
    process = subprocess.run(
        args,
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    if process.returncode and not allow_failure:
        raise BenchmarkError(
            process.stderr.strip() or "command failed: " + " ".join(args)
        )
    return process.stdout.strip()


def git_root(path: str | Path | None = None) -> Path:
    start = Path(path or Path.cwd()).resolve()
    relative = _run(start, "git", "rev-parse", "--show-cdup")
    return (start / relative).resolve()


def git_commit(root: Path, value: str = "HEAD") -> str:
    return _run(root, "git", "rev-parse", value)


def _extract_function_text(source: str, symbol: str) -> tuple[Function, str]:
    matches = [item for item in parse_functions(source) if item.symbol == symbol]
    if len(matches) != 1:
        raise BenchmarkError(
            f"function {symbol!r} resolved to {len(matches)} definitions"
        )
    function = matches[0]
    return function, function_text(source, function).rstrip() + "\n"


def extract_function(path: Path, symbol: str) -> tuple[Function, str]:
    return _extract_function_text(path.read_text(encoding="utf-8"), symbol)


def _strip_comments(text: str) -> str:
    out: list[str] = []
    index = 0
    state = "code"
    while index < len(text):
        char = text[index]
        nxt = text[index + 1] if index + 1 < len(text) else ""
        if state == "code":
            if char == "/" and nxt == "/":
                state = "line"
                out.extend("  ")
                index += 2
                continue
            if char == "/" and nxt == "*":
                state = "block"
                out.extend("  ")
                index += 2
                continue
            if char == '"':
                state = "string"
            elif char == "'":
                state = "char"
            out.append(char)
            index += 1
            continue
        if state == "line":
            if char == "\n":
                state = "code"
                out.append(char)
            else:
                out.append(" ")
            index += 1
            continue
        if state == "block":
            if char == "*" and nxt == "/":
                out.extend("  ")
                state = "code"
                index += 2
            else:
                out.append("\n" if char == "\n" else " ")
                index += 1
            continue
        out.append(char)
        if char == "\\" and index + 1 < len(text):
            out.append(text[index + 1])
            index += 2
            continue
        if state == "string" and char == '"':
            state = "code"
        elif state == "char" and char == "'":
            state = "code"
        index += 1
    return "".join(out)


_TOKEN_RE = re.compile(
    r"""
    (?:u8|u16|u32|u64|s8|s16|s32|s64|f32|f64)\b
    |[A-Za-z_]\w*
    |0[xX][0-9A-Fa-f]+(?:[uUlL]+)?
    |(?:\d+\.\d*|\.\d+|\d+)(?:[eE][+-]?\d+)?[fFuUlL]*
    |"(?:\\.|[^"\\])*"
    |'(?:\\.|[^'\\])*'
    |<<=|>>=|==|!=|<=|>=|->|\+\+|--|&&|\|\||<<|>>|\+=|-=|\*=|/=|%=|&=|\|=|\^=
    |[{}()\[\];,.?:~!%^&*+\-/|<>=]
    """,
    re.VERBOSE,
)


def c_tokens(text: str) -> list[str]:
    return _TOKEN_RE.findall(_strip_comments(text))


def compare_source(reference: str, candidate: str) -> SourceComparison:
    left = c_tokens(reference)
    right = c_tokens(candidate)
    return SourceComparison(
        exact_tokens=left == right,
        token_similarity=difflib.SequenceMatcher(None, left, right).ratio(),
        reference_tokens=len(left),
        candidate_tokens=len(right),
    )


def normalize_assembly(text: str) -> list[str]:
    ignored = (
        ".file",
        ".ident",
        ".loc",
        ".cfi_",
        ".addrsig",
        ".section .note",
        ".note.GNU-stack",
    )
    lines: list[str] = []
    labels: dict[str, str] = {}

    def label(match: re.Match[str]) -> str:
        raw = match.group(0)
        if raw not in labels:
            labels[raw] = f".L{len(labels)}"
        return labels[raw]

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(ignored):
            continue
        line = re.sub(r"\s+#.*$", "", line)
        line = re.sub(r"\s+//.*$", "", line)
        line = re.sub(r"\s+;.*$", "", line)
        if not line:
            continue
        line = re.sub(r"\.L(?:BB|tmp|CPI|JTI)?[A-Za-z0-9_.$]*", label, line)
        line = re.sub(r"\s+", " ", line)
        line = re.sub(r"\s*,\s*", ",", line)
        lines.append(line)
    return lines


def compare_assembly(
    target: str | None, candidate: str | None
) -> AssemblyComparison:
    if target is None or candidate is None:
        return AssemblyComparison("not-run", None, None, 0, 0)
    left = normalize_assembly(target)
    right = normalize_assembly(candidate)
    return AssemblyComparison(
        status="compared",
        exact=left == right,
        similarity=difflib.SequenceMatcher(None, left, right).ratio(),
        target_lines=len(left),
        candidate_lines=len(right),
    )


def _line_numbers(
    text: str, pattern: re.Pattern[str], limit: int = 8
) -> tuple[int, ...]:
    return tuple(
        text.count("\n", 0, match.start()) + 1
        for match in list(pattern.finditer(text))[:limit]
    )


def _finding(
    text: str,
    *,
    finding_id: str,
    category: str,
    severity: int,
    message: str,
    pattern: re.Pattern[str],
    confidence: str = "medium",
) -> Finding | None:
    matches = list(pattern.finditer(text))
    if not matches:
        return None
    return Finding(
        finding_id,
        category,
        severity,
        len(matches),
        message,
        _line_numbers(text, pattern),
        confidence,
    )


_ORGANIC_RULES: tuple[tuple[str, str, int, str, re.Pattern[str], str], ...] = (
    (
        "compiler-pragma",
        "compiler_control",
        14,
        "Compiler pragma requires direct source-shape evidence.",
        re.compile(r"(?m)^\s*#\s*pragma\b"),
        "high",
    ),
    (
        "forced-inline-control",
        "compiler_control",
        14,
        "Forced inline or no-inline control may be match-only scaffolding.",
        re.compile(
            r"\b(?:NOINLINE|FORCEINLINE|FORCE_INLINE|always_inline|never_inline)\b",
            re.IGNORECASE,
        ),
        "high",
    ),
    (
        "inline-assembly",
        "compiler_control",
        18,
        "Inline assembly needs evidence that the original source used assembly.",
        re.compile(r"\b(?:asm|__asm__)\s*(?:\(|\{)"),
        "high",
    ),
    (
        "dead-preprocessor-branch",
        "compiler_control",
        14,
        "A compile-time dead branch can hide code-generation scaffolding.",
        re.compile(r"(?m)^\s*#\s*if\s+0\b"),
        "high",
    ),
    (
        "foreign-include-guard",
        "compiler_control",
        14,
        "Defining a header guard from C can manipulate declaration visibility.",
        re.compile(r"(?m)^\s*#\s*define\s+_[A-Z0-9_]+_H\b"),
        "high",
    ),
    (
        "codegen-volatile",
        "compiler_control",
        6,
        "volatile may be legitimate, but it needs contract or hardware evidence.",
        re.compile(r"\bvolatile\b"),
        "medium",
    ),
    (
        "register-keyword",
        "compiler_control",
        4,
        "register may be historical style or allocation coercion; review it.",
        re.compile(r"\bregister\b"),
        "medium",
    ),
    (
        "cast-ladder",
        "compiler_control",
        7,
        "Adjacent cast ladders often indicate type or allocation coercion.",
        re.compile(r"\([^()]{1,40}\)\s*\([^()]{1,40}\)\s*[A-Za-z_(]"),
        "medium",
    ),
    (
        "opaque-storage",
        "semantic_debt",
        4,
        "Opaque raw/blob/tail/padding storage remains semantic recovery debt.",
        re.compile(
            r"\b(?:raw|blob|tail|opaque|padding|reserved|pad|unk)[A-Za-z0-9_]*\s*\[",
            re.IGNORECASE,
        ),
        "high",
    ),
    (
        "opaque-identifier",
        "semantic_debt",
        1,
        "Opaque identifier is honest but marks unrecovered semantics.",
        re.compile(r"\b(?:unk|reserved|pad)[A-Za-z0-9_]*\b", re.IGNORECASE),
        "high",
    ),
    (
        "address-derived-symbol",
        "semantic_debt",
        1,
        "Address-derived symbol preserves identity but is not semantic naming.",
        re.compile(r"\b(?:fn|lbl|data)_(?:\d+_)?[0-9A-Fa-f]{4,}\b"),
        "high",
    ),
)


def _redundant_drain_condition(text: str) -> Finding | None:
    pattern = re.compile(
        r"""
        while\s*\(\s*
        (?P<expr>[A-Za-z_]\w*(?:(?:->|\.)[A-Za-z_]\w*)*)
        \s*!=\s*0\s*\)\s*\{
        (?P<body>.*?)
        \}\s*
        if\s*\(\s*(?P=expr)\s*==\s*0\s*\)
        """,
        re.DOTALL | re.VERBOSE,
    )
    matches: list[re.Match[str]] = []
    for match in pattern.finditer(text):
        expression = re.escape(match.group("expr"))
        if re.search(
            rf"(?:{expression}\s*--|--\s*{expression}|{expression}\s*-=\s*1)",
            match.group("body"),
        ):
            matches.append(match)
    if not matches:
        return None
    return Finding(
        "guaranteed-post-loop-condition",
        "redundancy",
        4,
        len(matches),
        "Condition is guaranteed after a loop that drains the same value to zero; preserve only with source-shape evidence.",
        tuple(text.count("\n", 0, item.start()) + 1 for item in matches[:8]),
        "medium",
    )


def score_organicity(text: str) -> Organicity:
    cleaned = _strip_comments(text)
    findings: list[Finding] = []
    for finding_id, category, severity, message, pattern, confidence in _ORGANIC_RULES:
        value = _finding(
            cleaned,
            finding_id=finding_id,
            category=category,
            severity=severity,
            message=message,
            pattern=pattern,
            confidence=confidence,
        )
        if value:
            findings.append(value)
    redundant = _redundant_drain_condition(cleaned)
    if redundant:
        findings.append(redundant)
    deductions: dict[str, int] = {}
    for item in findings:
        deductions[item.category] = deductions.get(item.category, 0) + item.deduction
    score = max(0, 100 - sum(deductions.values()))
    high_risk = any(
        item.category == "compiler_control" and item.severity >= 12
        for item in findings
    )
    if score >= 95 and not high_risk:
        rating = "strongly-organic"
    elif score >= 85 and not high_risk:
        rating = "plausibly-organic"
    elif score >= 70:
        rating = "needs-source-shape-review"
    else:
        rating = "match-shaped-or-opaque"
    return Organicity(
        score=score,
        rating=rating,
        findings=tuple(findings),
        category_deductions=deductions,
        human_review_required=bool(findings),
    )


def score_pair(
    reference: str,
    candidate: str,
    *,
    target_assembly: str | None = None,
    candidate_assembly: str | None = None,
) -> dict[str, Any]:
    source = compare_source(reference, candidate)
    assembly = compare_assembly(target_assembly, candidate_assembly)
    reference_organic = score_organicity(reference)
    candidate_organic = score_organicity(candidate)
    reference_ids = {item.id for item in reference_organic.findings}
    candidate_ids = {item.id for item in candidate_organic.findings}
    if assembly.exact is True:
        binary_status = "exact-surrogate-or-target"
    elif assembly.exact is False:
        binary_status = "different"
    else:
        binary_status = "not-run"
    return {
        "schema_version": SCHEMA_VERSION,
        "scored_at": _now(),
        "binary_equivalence": binary_status,
        "source": source.as_dict(),
        "assembly": assembly.as_dict(),
        "organicity": {
            "reference": reference_organic.as_dict(),
            "candidate": candidate_organic.as_dict(),
            "inherited_reference_debt": sorted(reference_ids & candidate_ids),
            "candidate_only_debt": sorted(candidate_ids - reference_ids),
            "reference_only_debt": sorted(reference_ids - candidate_ids),
        },
        "success_dimensions": {
            "assembly_exact": assembly.exact,
            "source_tokens_exact": source.exact_tokens,
            "candidate_organic_score": candidate_organic.score,
            "candidate_organic_rating": candidate_organic.rating,
            "independent_human_review_required": candidate_organic.human_review_required,
        },
    }


def render_score(result: Mapping[str, Any]) -> str:
    source = result.get("source", {})
    assembly = result.get("assembly", {})
    organicity = result.get("organicity", {})
    candidate = (
        organicity.get("candidate", {})
        if isinstance(organicity, Mapping)
        else {}
    )
    inherited = (
        organicity.get("inherited_reference_debt", [])
        if isinstance(organicity, Mapping)
        else []
    )
    only = (
        organicity.get("candidate_only_debt", [])
        if isinstance(organicity, Mapping)
        else []
    )
    lines = [
        "# Blind recovery score",
        "",
        f"- Binary comparison: `{result.get('binary_equivalence')}`",
        f"- Assembly exact: `{assembly.get('exact')}`",
        f"- Assembly similarity: `{assembly.get('similarity')}`",
        f"- Source tokens exact: `{source.get('exact_tokens')}`",
        f"- Source-token similarity: `{source.get('token_similarity')}`",
        f"- Candidate organicity: `{candidate.get('score')}/100` — `{candidate.get('rating')}`",
        f"- Inherited retained-source debt: `{', '.join(inherited) or 'none'}`",
        f"- Candidate-only debt: `{', '.join(only) or 'none'}`",
        "",
        "## Organicity findings",
        "",
    ]
    findings = (
        candidate.get("findings", [])
        if isinstance(candidate, Mapping)
        else []
    )
    if findings:
        for item in findings:
            lines.append(
                f"- `{item.get('id')}` [{item.get('category')}, -{item.get('deduction')}]: "
                f"{item.get('message')} Lines: {item.get('lines')}"
            )
    else:
        lines.append("- None detected by the automated review.")
    lines += [
        "",
        "Automated organicity is a review aid, not proof of historical authenticity. "
        "Exact source similarity can reproduce debt already present in the retained source.",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _load_manifest(root: Path, manifest_path: Path) -> dict[str, Any]:
    path = manifest_path if manifest_path.is_absolute() else root / manifest_path
    value = _read_json(path)
    if value.get("schema_version") != SCHEMA_VERSION:
        raise BenchmarkError(f"{path}: unsupported schema_version")
    cases = value.get("cases")
    if not isinstance(cases, list) or not all(
        isinstance(item, str) for item in cases
    ):
        raise BenchmarkError(f"{path}: cases must be a string list")
    value["_path"] = path
    return value


def _case_paths(root: Path, manifest_path: Path) -> list[Path]:
    manifest = _load_manifest(root, manifest_path)
    base = Path(manifest["_path"]).parent
    return [(base / value).resolve() for value in manifest["cases"]]


def validate_case(
    root: Path, case_path: Path, *, replay: bool = False
) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    case = _read_json(case_path)
    where = (
        case_path.relative_to(root)
        if case_path.is_relative_to(root)
        else case_path
    )
    if case.get("schema_version") != SCHEMA_VERSION:
        errors.append(f"{where}: schema_version must be {SCHEMA_VERSION}")
    status = case.get("status")
    if status not in CASE_STATUSES:
        errors.append(f"{where}: invalid status {status!r}")
    for key in (
        "id",
        "source",
        "function",
        "source_commit",
        "reference_sha256",
    ):
        if not isinstance(case.get(key), str) or not case.get(key):
            errors.append(f"{where}: {key} is required")
    artifacts = case.get("artifacts", {})
    if not isinstance(artifacts, dict):
        errors.append(f"{where}: artifacts must be an object")
        artifacts = {}
    base = case_path.parent
    if status == LEGACY:
        warnings.append(
            f"{where}: legacy result is reported but not independently replayable"
        )
        return errors, warnings
    if re.fullmatch(
        r"[0-9a-f]{64}", str(case.get("reference_sha256", ""))
    ) is None:
        errors.append(
            f"{where}: reproducible case requires a lowercase SHA-256 reference hash"
        )
    required = (
        "evidence",
        "candidate",
        "target_assembly",
        "candidate_assembly",
        "result",
    )
    for key in required:
        relative = artifacts.get(key)
        if not isinstance(relative, str) or not relative:
            errors.append(f"{where}: reproducible case requires artifacts.{key}")
            continue
        candidate = base / relative
        if not candidate.is_file():
            errors.append(f"{where}: missing artifact {relative}")
    candidate_path = base / str(artifacts.get("candidate", ""))
    expected_candidate_hash = case.get("candidate_sha256")
    if candidate_path.is_file() and isinstance(expected_candidate_hash, str):
        actual = sha256_file(candidate_path)
        if actual != expected_candidate_hash:
            errors.append(f"{where}: candidate SHA-256 mismatch")
    blindness = case.get("blindness", {})
    if not isinstance(blindness, dict):
        errors.append(f"{where}: blindness must be an object")
        blindness = {}
    for key in (
        "reference_withheld",
        "candidate_frozen_before_reveal",
        "raw_candidate_preserved",
        "raw_evidence_preserved",
    ):
        if blindness.get(key) is not True:
            errors.append(f"{where}: blindness.{key} must be true")
    if replay and not errors:
        errors.extend(replay_case(root, case_path, write=False))
    return errors, warnings


def audit_repository(
    root: Path,
    manifest_path: Path = DEFAULT_MANIFEST,
    *,
    replay: bool = False,
) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    identifiers: set[str] = set()
    case_paths = _case_paths(root, manifest_path)
    for path in case_paths:
        if not path.is_file():
            errors.append(f"missing benchmark case: {path}")
            continue
        case = _read_json(path)
        case_id = case.get("id")
        if isinstance(case_id, str):
            if case_id in identifiers:
                errors.append(f"duplicate benchmark case id: {case_id}")
            identifiers.add(case_id)
        case_errors, case_warnings = validate_case(
            root, path, replay=replay
        )
        errors.extend(case_errors)
        warnings.extend(case_warnings)
    return {
        "schema_version": SCHEMA_VERSION,
        "manifest": str(manifest_path),
        "cases": len(case_paths),
        "errors": sorted(set(errors)),
        "warnings": sorted(set(warnings)),
        "replay": replay,
    }


def _git_show_function(
    root: Path, commit: str, source: str, symbol: str
) -> str:
    text = _run(root, "git", "show", f"{commit}:{source}")
    _, value = _extract_function_text(text, symbol)
    return value


def replay_case(
    root: Path, case_path: Path, *, write: bool = False
) -> list[str]:
    case = _read_json(case_path)
    if case.get("status") != REPRODUCIBLE:
        return [f"{case_path}: legacy case cannot be replayed"]
    artifacts = case["artifacts"]
    base = case_path.parent
    reference = _git_show_function(
        root,
        str(case["source_commit"]),
        str(case["source"]),
        str(case["function"]),
    )
    if _sha256_bytes(reference.encode()) != case.get("reference_sha256"):
        return [f"{case_path}: reference SHA-256 mismatch at source commit"]
    candidate = (base / artifacts["candidate"]).read_text(encoding="utf-8")
    target_assembly = (base / artifacts["target_assembly"]).read_text(
        encoding="utf-8"
    )
    candidate_assembly = (base / artifacts["candidate_assembly"]).read_text(
        encoding="utf-8"
    )
    actual = score_pair(
        reference,
        candidate,
        target_assembly=target_assembly,
        candidate_assembly=candidate_assembly,
    )
    stored = _read_json(base / artifacts["result"])
    comparable_keys = (
        "binary_equivalence",
        "source",
        "assembly",
        "organicity",
        "success_dimensions",
    )
    errors = [
        f"{case_path}: replay differs for {key}"
        for key in comparable_keys
        if actual.get(key) != stored.get(key)
    ]
    if write and not errors:
        _write_json(base / artifacts["result"], actual)
        report = artifacts.get("report")
        if isinstance(report, str):
            (base / report).write_text(
                render_score(actual), encoding="utf-8"
            )
    return errors


def prepare_run(
    root: Path,
    *,
    trial_id: str,
    source_path: str,
    symbol: str,
    evidence_path: Path,
    target_assembly_path: Path,
    run_dir: Path | None = None,
) -> Path:
    source = root / source_path
    if not source.is_file():
        raise BenchmarkError(f"missing source: {source}")
    if not evidence_path.is_file():
        raise BenchmarkError(f"missing evidence: {evidence_path}")
    if not target_assembly_path.is_file():
        raise BenchmarkError(f"missing target assembly: {target_assembly_path}")
    function, reference = extract_function(source, symbol)
    destination = run_dir or (
        root
        / DEFAULT_RUN_ROOT
        / f"{trial_id}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
    )
    destination = destination.resolve()
    if destination.exists() and any(destination.iterdir()):
        raise BenchmarkError(f"run directory is not empty: {destination}")
    private = destination / "private"
    packet = destination / "packet"
    private.mkdir(parents=True, exist_ok=True)
    packet.mkdir(parents=True, exist_ok=True)
    (private / "reference.c").write_text(reference, encoding="utf-8")
    shutil.copy2(evidence_path, packet / "evidence.md")
    shutil.copy2(target_assembly_path, packet / "target.s")
    signature = function.signature.rstrip(";") + ";\n"
    (packet / "signature.h").write_text(signature, encoding="utf-8")
    (destination / "candidate.c").write_text(
        signature.rstrip(";\n")
        + "\n{\n    /* Blind candidate goes here. */\n}\n",
        encoding="utf-8",
    )
    seal = {
        "schema_version": SCHEMA_VERSION,
        "id": trial_id,
        "source": source_path,
        "function": symbol,
        "source_commit": git_commit(root),
        "reference_sha256": _sha256_bytes(reference.encode()),
        "evidence_sha256": sha256_file(packet / "evidence.md"),
        "target_assembly_sha256": sha256_file(packet / "target.s"),
        "created_at": _now(),
        "candidate_frozen": False,
    }
    _write_json(destination / "seal.json", seal)
    return destination


def freeze_candidate(
    run_dir: Path, candidate_path: Path, *, force: bool = False
) -> dict[str, Any]:
    seal_path = run_dir / "seal.json"
    seal = _read_json(seal_path)
    frozen_path = run_dir / "frozen-candidate.c"
    metadata_path = run_dir / "candidate.json"
    if metadata_path.exists() and not force:
        raise BenchmarkError(
            "candidate is already frozen; use --force to replace"
        )
    if not candidate_path.is_file():
        raise BenchmarkError(f"missing candidate: {candidate_path}")
    shutil.copy2(candidate_path, frozen_path)
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "candidate_sha256": sha256_file(frozen_path),
        "frozen_at": _now(),
        "candidate_path": frozen_path.name,
    }
    _write_json(metadata_path, metadata)
    seal["candidate_frozen"] = True
    seal["candidate_sha256"] = metadata["candidate_sha256"]
    seal["candidate_frozen_at"] = metadata["frozen_at"]
    _write_json(seal_path, seal)
    return metadata


def score_run(
    run_dir: Path,
    *,
    candidate_assembly_path: Path | None = None,
) -> dict[str, Any]:
    seal = _read_json(run_dir / "seal.json")
    candidate_meta = _read_json(run_dir / "candidate.json")
    if seal.get("candidate_frozen") is not True:
        raise BenchmarkError("candidate must be frozen before scoring")
    candidate_path = run_dir / str(candidate_meta["candidate_path"])
    if sha256_file(candidate_path) != candidate_meta.get("candidate_sha256"):
        raise BenchmarkError("frozen candidate changed after freeze")
    reference = (run_dir / "private/reference.c").read_text(encoding="utf-8")
    if _sha256_bytes(reference.encode()) != seal.get("reference_sha256"):
        raise BenchmarkError("private reference does not match seal")
    target_assembly = (run_dir / "packet/target.s").read_text(
        encoding="utf-8"
    )
    candidate_assembly = (
        candidate_assembly_path.read_text(encoding="utf-8")
        if candidate_assembly_path and candidate_assembly_path.is_file()
        else None
    )
    result = score_pair(
        reference,
        candidate_path.read_text(encoding="utf-8"),
        target_assembly=target_assembly,
        candidate_assembly=candidate_assembly,
    )
    result.update(
        {
            "id": seal.get("id"),
            "target_source": seal.get("source"),
            "function": seal.get("function"),
            "source_commit": seal.get("source_commit"),
            "reference_sha256": seal.get("reference_sha256"),
            "candidate_sha256": candidate_meta.get("candidate_sha256"),
            "candidate_frozen_at": candidate_meta.get("frozen_at"),
            "blindness": {
                "reference_withheld": True,
                "candidate_frozen_before_reveal": True,
                "raw_candidate_preserved": True,
                "raw_evidence_preserved": True,
            },
        }
    )
    _write_json(run_dir / "result.json", result)
    (run_dir / "report.md").write_text(
        render_score(result), encoding="utf-8"
    )
    return result


def archive_run(root: Path, run_dir: Path, destination: Path) -> Path:
    seal = _read_json(run_dir / "seal.json")
    candidate_meta = _read_json(run_dir / "candidate.json")
    result = _read_json(run_dir / "result.json")
    candidate_assembly = run_dir / "candidate.s"
    if not candidate_assembly.is_file():
        raise BenchmarkError(
            "candidate.s is required before archival; preserve the exact assembly compared"
        )
    destination = (
        destination if destination.is_absolute() else root / destination
    )
    if destination.exists() and any(destination.iterdir()):
        raise BenchmarkError(
            f"archive destination is not empty: {destination}"
        )
    destination.mkdir(parents=True, exist_ok=True)
    shutil.copy2(
        run_dir / "packet/evidence.md", destination / "evidence.md"
    )
    shutil.copy2(run_dir / "packet/target.s", destination / "target.s")
    shutil.copy2(
        run_dir / str(candidate_meta["candidate_path"]),
        destination / "candidate.c",
    )
    shutil.copy2(candidate_assembly, destination / "candidate.s")
    _write_json(destination / "result.json", result)
    (destination / "report.md").write_text(
        render_score(result), encoding="utf-8"
    )
    case = {
        "schema_version": SCHEMA_VERSION,
        "id": seal["id"],
        "status": REPRODUCIBLE,
        "source": seal["source"],
        "function": seal["function"],
        "source_commit": seal["source_commit"],
        "reference_sha256": seal["reference_sha256"],
        "candidate_sha256": candidate_meta["candidate_sha256"],
        "artifacts": {
            "evidence": "evidence.md",
            "candidate": "candidate.c",
            "target_assembly": "target.s",
            "candidate_assembly": "candidate.s",
            "result": "result.json",
            "report": "report.md",
        },
        "blindness": result.get("blindness", {}),
        "archived_at": _now(),
    }
    _write_json(destination / "case.json", case)
    return destination / "case.json"


def _print_audit(value: Mapping[str, Any]) -> None:
    print(f"blind benchmark cases: {value.get('cases', 0)}")
    for error in value.get("errors", []):
        print(f"ERROR: {error}")
    for warning in value.get("warnings", []):
        print(f"WARN: {warning}")
    if not value.get("errors"):
        print("blind benchmark audit: PASS")


def _resolve(root: Path, value: str | Path) -> Path:
    path = Path(value).expanduser()
    return (path if path.is_absolute() else root / path).resolve()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root")
    sub = parser.add_subparsers(dest="command", required=True)

    audit = sub.add_parser(
        "audit", help="validate preserved benchmark cases"
    )
    audit.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    audit.add_argument("--replay", action="store_true")
    audit.add_argument("--strict", action="store_true")
    audit.add_argument("--json", action="store_true")

    organicity = sub.add_parser(
        "organicity", help="score organic-source indicators"
    )
    organicity.add_argument("path")
    organicity.add_argument("--function")
    organicity.add_argument("--json", action="store_true")

    score = sub.add_parser(
        "score", help="score one reference/candidate pair"
    )
    score.add_argument("--reference", required=True)
    score.add_argument("--candidate", required=True)
    score.add_argument("--function")
    score.add_argument("--target-assembly")
    score.add_argument("--candidate-assembly")
    score.add_argument("--output")

    prepare = sub.add_parser(
        "prepare", help="create a sealed local holdout run"
    )
    prepare.add_argument("--id", required=True)
    prepare.add_argument("--source", required=True)
    prepare.add_argument("--function", required=True)
    prepare.add_argument("--evidence", required=True)
    prepare.add_argument("--target-assembly", required=True)
    prepare.add_argument("--run-dir")

    freeze = sub.add_parser(
        "freeze", help="freeze a candidate before reveal/scoring"
    )
    freeze.add_argument("--run-dir", required=True)
    freeze.add_argument("--candidate", required=True)
    freeze.add_argument("--force", action="store_true")

    score_run_parser = sub.add_parser(
        "score-run", help="score a frozen holdout run"
    )
    score_run_parser.add_argument("--run-dir", required=True)
    score_run_parser.add_argument("--candidate-assembly")

    archive = sub.add_parser(
        "archive", help="archive a replayable completed run"
    )
    archive.add_argument("--run-dir", required=True)
    archive.add_argument("--destination", required=True)

    replay = sub.add_parser("replay", help="replay one archived case")
    replay.add_argument("case")

    args = parser.parse_args()
    try:
        root = git_root(args.root)
        if args.command == "audit":
            value = audit_repository(
                root,
                Path(args.manifest),
                replay=args.replay,
            )
            if args.json:
                print(json.dumps(value, indent=2))
            else:
                _print_audit(value)
            failed = bool(value["errors"]) or (
                args.strict and bool(value["warnings"])
            )
            return 1 if failed else 0
        if args.command == "organicity":
            path = _resolve(root, args.path)
            text = path.read_text(encoding="utf-8")
            if args.function:
                _, text = _extract_function_text(text, args.function)
            value = score_organicity(text).as_dict()
            if args.json:
                print(json.dumps(value, indent=2))
            else:
                print(
                    f"organicity: {value['score']}/100 ({value['rating']})"
                )
                for item in value["findings"]:
                    print(
                        f"- {item['id']}: {item['message']} lines={item['lines']}"
                    )
            return 0
        if args.command == "score":
            reference_path = _resolve(root, args.reference)
            candidate_path = _resolve(root, args.candidate)
            reference = reference_path.read_text(encoding="utf-8")
            candidate = candidate_path.read_text(encoding="utf-8")
            if args.function:
                _, reference = _extract_function_text(
                    reference, args.function
                )
                _, candidate = _extract_function_text(
                    candidate, args.function
                )
            target_assembly = (
                _resolve(root, args.target_assembly).read_text(
                    encoding="utf-8"
                )
                if args.target_assembly
                else None
            )
            candidate_assembly = (
                _resolve(root, args.candidate_assembly).read_text(
                    encoding="utf-8"
                )
                if args.candidate_assembly
                else None
            )
            result = score_pair(
                reference,
                candidate,
                target_assembly=target_assembly,
                candidate_assembly=candidate_assembly,
            )
            if args.output:
                output = _resolve(root, args.output)
                _write_json(output, result)
                output.with_suffix(".md").write_text(
                    render_score(result), encoding="utf-8"
                )
                print(f"wrote {output}")
            else:
                print(json.dumps(result, indent=2))
            return 0
        if args.command == "prepare":
            destination = prepare_run(
                root,
                trial_id=args.id,
                source_path=args.source,
                symbol=args.function,
                evidence_path=_resolve(root, args.evidence),
                target_assembly_path=_resolve(
                    root, args.target_assembly
                ),
                run_dir=(
                    _resolve(root, args.run_dir)
                    if args.run_dir
                    else None
                ),
            )
            print(destination)
            return 0
        if args.command == "freeze":
            value = freeze_candidate(
                _resolve(root, args.run_dir),
                _resolve(root, args.candidate),
                force=args.force,
            )
            print(json.dumps(value, indent=2))
            return 0
        if args.command == "score-run":
            run_dir = _resolve(root, args.run_dir)
            assembly = (
                _resolve(root, args.candidate_assembly)
                if args.candidate_assembly
                else None
            )
            if assembly:
                shutil.copy2(assembly, run_dir / "candidate.s")
            result = score_run(
                run_dir, candidate_assembly_path=assembly
            )
            print(render_score(result), end="")
            return 0
        if args.command == "archive":
            value = archive_run(
                root,
                _resolve(root, args.run_dir),
                Path(args.destination),
            )
            print(value)
            return 0
        errors = replay_case(
            root, _resolve(root, args.case), write=False
        )
        for error in errors:
            print(f"ERROR: {error}")
        if not errors:
            print("blind benchmark replay: PASS")
        return 1 if errors else 0
    except (BenchmarkError, OSError, RecoveryError) as exc:
        print(f"error: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
