"""Execute a bounded reviewed source-shape plan, stopping at a verified gain.

No arbitrary source templates, ABI guesses, permutations, or retries.  The plan
approves transformation families and source constraints once; the existing
compiler/evaluator measures generated bytes.  This is not an inverse compiler:
missing source evidence is an explicit terminal outcome, never a ranked guess.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import sys
import time
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools import compile_recovery_candidate as compiler
from tools import recovery_evaluate as evaluator
from tools import recovery_frontier as frontier
from tools import recovery_search_batch as batch
from tools import recovery_source_shapes as shapes
from tools import recovery_contract_search as contracts

SCHEMA = "recovery_guided_search/v1"
MAX_REQUESTS = 16
MAX_CANDIDATES = 8
MAX_PLAN_BYTES = 256 * 1024
FAMILIES = shapes.FAMILIES | {contracts.FAMILY}
IDENT = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]{0,79}\Z")


def _sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _descriptor(root: Path, value: dict) -> tuple[Path, dict]:
    if not isinstance(value, dict) or not isinstance(value.get("path"), str):
        raise ValueError("evidence path/hash descriptor required")
    path = frontier.local(root, Path(value["path"]))
    _, actual = frontier.read_bound(root, path, frontier.REPORT_LIMIT)
    if actual["sha256"] != value.get("sha256"):
        raise ValueError(f"evidence changed: {path}")
    return path, actual


def _changed_rows(document: dict, function: str) -> set[int]:
    pair = evaluator._diagnostic_rows(document, function)
    if pair is None:
        raise ValueError(f"function absent from current strict report: {function}")
    return set(evaluator._diagnostic_mismatches(*pair))


def _load(root: Path, index: Path, plan: Path) -> tuple[dict, dict, bytes, dict[str, str]]:
    index_raw, index_desc = frontier.read_bound(root, index, frontier.INDEX_LIMIT)
    base = frontier.load_json(index_raw)
    frontier.verify(root, base)
    if base.get("compile_binding") != "receipt_hashes_match" or base.get("data_functions") is None:
        raise ValueError("source-bound whole-owner strict/data frontier required")
    plan_raw, plan_desc = frontier.read_bound(root, plan, MAX_PLAN_BYTES)
    spec = frontier.load_json(plan_raw)
    if not isinstance(spec, dict) or spec.get("schema") != SCHEMA or spec.get("root_reviewed") is not True:
        raise ValueError("reviewed guided-search family plan required")
    source_desc = base["inputs"]["source"]
    source, actual = frontier.read_bound(root, Path(source_desc["path"]), shapes.LIMIT)
    if actual != source_desc or spec.get("source_sha256") != actual["sha256"]:
        raise ValueError("guided plan source binding is stale")
    if spec.get("baseline_index_sha256") != index_desc["sha256"]:
        raise ValueError("guided plan frontier binding is stale")
    requests = spec.get("requests")
    if not isinstance(requests, list) or not 1 <= len(requests) <= MAX_REQUESTS:
        raise ValueError("1..16 reviewed source-constraint requests required")
    report_raw, report_desc = frontier.read_bound(root, Path(base["inputs"]["strict_report"]["path"]), frontier.REPORT_LIMIT)
    if report_desc != base["inputs"]["strict_report"]:
        raise ValueError("strict report binding changed during plan validation")
    report = frontier.load_json(report_raw)
    known = {row["function"] for row in base["functions"]}
    frozen = {str(index): index_desc["sha256"], str(plan): plan_desc["sha256"],
              str(frontier.local(root, Path(source_desc["path"]))): source_desc["sha256"],
              str(frontier.local(root, Path(report_desc["path"]))): report_desc["sha256"]}
    if spec.get("working_source") is not None:
        source, working_frozen = evaluator.working_source_binding(root, index, base, spec["working_source"])
        frozen.update(working_frozen)
        actual = {"sha256": _sha(source)}
    ids: set[str] = set()
    for req in requests:
        if not isinstance(req, dict) or not isinstance(req.get("id"), str) or not IDENT.fullmatch(req["id"]):
            raise ValueError("bounded request identifier required")
        if req["id"] in ids or req.get("function") not in known:
            raise ValueError("duplicate request or unknown function")
        ids.add(req["id"])
        rows = req.get("target_rows")
        if (not isinstance(rows, list) or not 1 <= len(rows) <= 256 or
                any(isinstance(row, bool) or not isinstance(row, int) or row < 0 for row in rows) or
                len(rows) != len(set(rows))):
            raise ValueError("distinct actual residual target rows required")
        if not set(rows) <= _changed_rows(report, req["function"]):
            raise ValueError(f"predicted rows are not current residuals: {req['id']}")
        if not isinstance(req.get("constraints"), dict) or req["constraints"].get("source_sha256") != actual["sha256"]:
            raise ValueError("source constraints must bind the current source")
        families = req.get("families")
        if req.get('composed') is not None:
            stages = req['composed'].get('stages', [])
            if (len(requests) != 1 or families not in (None, [contracts.COMPOSED_FAMILY])
                    or not isinstance(stages, list) or len(stages) != 2
                    or [s.get('family') for s in stages] != [contracts.FAMILY, 'sequence_result_consumer']
                    or any(s.get('constraints', {}).get('source_sha256') != actual['sha256'] for s in stages)):
                raise ValueError('one bounded canonical-contract/sequence composition request required')
            families = req['families'] = [contracts.COMPOSED_FAMILY]
            for module in (contracts, contracts.repair, shapes):
                implementation_path = Path(module.__file__).resolve()
                frozen[str(implementation_path)] = compiler.digest(implementation_path)
        if not isinstance(families, list) or not families or not set(families) <= (FAMILIES | {contracts.COMPOSED_FAMILY}):
            raise ValueError("only installed approved natural source families may run")
        if spec.get("working_source") is not None and set(families) & {contracts.FAMILY, contracts.COMPOSED_FAMILY}:
            raise ValueError("contract generation from a working source is not supported")
        if contracts.FAMILY in families and len(families) != 1:
            raise ValueError("canonical contract repair is one composed family, not a mixed search")
        evidence = req.get("evidence")
        if not isinstance(evidence, list) or not 1 <= len(evidence) <= 8:
            raise ValueError("1..8 source-constraint evidence bindings required")
        for item in evidence:
            path, desc = _descriptor(root, item)
            frozen[str(path)] = desc["sha256"]
    for module in (shapes, contracts, contracts.repair):
        frozen[str(Path(module.__file__).resolve())] = compiler.digest(Path(module.__file__))
    return spec, base, source, frozen


def run(*, root: Path, index: Path, plan: Path, out_dir: Path, scratch: Path,
        source_relpath: str, object_relpath: str, compiler_script: Path,
        objdiff: Path, readelf: Path, tools: list[Path] | None = None,
        max_candidates: int = 8, timeout: float = 300, retain: bool = False) -> dict[str, Any]:
    """Generate, measure, learn, and optionally independently retain one gain."""
    root = Path(root).absolute()
    index, plan, out_dir = [frontier.local(root, Path(p)) for p in (index, plan, out_dir)]
    out_dir.relative_to(root / "build")
    if out_dir.exists():
        raise ValueError(f"guided output is immutable and already exists: {out_dir}")
    if isinstance(max_candidates, bool) or not isinstance(max_candidates, int) or not 1 <= max_candidates <= MAX_CANDIDATES:
        raise ValueError("candidate budget must be 1..8")
    if isinstance(timeout, bool) or not math.isfinite(timeout) or not 0 < timeout <= 1800:
        raise ValueError("guided deadline must be finite and at most 1800 seconds")
    spec, base, source, frozen = _load(root, index, plan)
    if frontier.local(root, root / source_relpath) != frontier.local(root, Path(base["inputs"]["source"]["path"])):
        raise ValueError("compiler source path differs from the verified frontier")
    if retain and spec.get("allow_retention") is not True:
        raise ValueError("plan does not approve automatic private source retention")
    started = time.monotonic()
    result: dict[str, Any] = {"schema": SCHEMA, "status": "no_generated_gain", "owner": base["owner"],
        "baseline_index_sha256": compiler.digest(index), "source_sha256": base["inputs"]["source"]["sha256"],
        "generated": 0, "dispatched": 0, "compiler_runs": 0, "skipped": [], "attempts": [],
        "retained": False, "authority_advanced": False, "linked_exact": False}

    def remaining() -> float:
        value = timeout - (time.monotonic() - started)
        if value <= 0:
            raise TimeoutError("guided-search deadline exhausted")
        return value

    def check() -> None:
        remaining()
        for name, expected in frozen.items():
            if compiler.digest(Path(name)) != expected:
                raise ValueError(f"guided-search input drift: {name}")
        frontier.verify(root, base)

    check()
    out_dir.mkdir(parents=True)
    if spec.get("working_source") is not None:
        result["working_source"] = spec["working_source"]
    seen = {_sha(source)}
    # Earlier actual mismatch is the deterministic priority. No percentage-only
    # ranking and no fabricated prediction that all groups will disappear.
    requests = sorted(spec["requests"], key=lambda r: (min(r["target_rows"]), -len(r["target_rows"]), r["id"]))
    try:
        for req in requests:
            check()
            try:
                if req.get('composed') is not None:
                    candidates = contracts.generate_composed(root, index, req['function'], source,
                                                            req['composed'], out_dir / ('generate-'+req['id']))
                elif req["families"] == [contracts.FAMILY]:
                    candidates = contracts.generate_shape(root, index, req["function"], req["constraints"],
                                                          out_dir / ("generate-" + req["id"]))
                else:
                    candidates = shapes.enumerate_shapes(source, req["function"], req["families"], req["constraints"])
            except ValueError as exc:
                result["skipped"].append({"request": req["id"], "status": "source_constraint_unavailable", "reason": str(exc)[:1000]})
                continue
            for shape in candidates:
                check()
                if shape.get("family") not in req["families"]:
                    raise ValueError("source generator returned an unapproved family")
                candidate = shape["candidate_source"]
                digest = _sha(candidate)
                if digest != shape["candidate_sha256"] or shape["source_sha256"] != _sha(source):
                    raise ValueError("source generator returned mismatched bytes/bindings")
                if digest in seen:
                    result["skipped"].append({"request": req["id"], "family": shape["family"], "status": "duplicate_generated_source"})
                    continue
                seen.add(digest)
                result["generated"] += 1
                if result["dispatched"] >= max_candidates:
                    result["status"] = "candidate_budget_exhausted"
                    return result
                ordinal = result["dispatched"]
                directory = out_dir / f"cell-{ordinal:02d}"
                directory.mkdir()
                candidate_path = directory / "candidate.c"
                compiler.atomic(candidate_path, candidate)
                selection_path = directory / "selection.json"
                generated_evidence = shape.get("evidence", [])
                if not isinstance(generated_evidence, list) or len(generated_evidence) > 4:
                    raise ValueError("bounded generator evidence required")
                for item in generated_evidence:
                    path, desc = _descriptor(root, item)
                    frozen[str(path)] = desc["sha256"]
                selection = {"schema": "recovery_generated_source_cell/v1", "request": req["id"],
                    "family": shape["family"], "function": req["function"], "source_sha256": _sha(source),
                    "candidate_sha256": digest, "target_rows": req["target_rows"], "rationale": shape["rationale"],
                    "generator_sha256": compiler.digest(Path(contracts.__file__ if shape["family"] == contracts.FAMILY else shapes.__file__)),
                    "evidence": [*req["evidence"], *generated_evidence],
                    "authority_advanced": False}
                if spec.get("working_source") is not None:
                    selection["source_lineage"] = evaluator.source_lineage(root, index, base, spec["working_source"], candidate)
                if req.get("hypothesis_binding") is not None:
                    selection["hypothesis_binding"] = req["hypothesis_binding"]
                compiler.atomic(selection_path, frontier.canonical(selection) + b"\n")
                manifest_path = directory / "manifest.json"
                manifest = {"schema": batch.SCHEMA, "root_reviewed": True, "causal_family": shape["family"],
                    "baseline_index_sha256": compiler.digest(index), "live_source_sha256": base["inputs"]["source"]["sha256"],
                    "candidates": [{"id": "generated", "source": candidate_path.relative_to(root).as_posix(),
                        "sha256": digest, "functions": [req["function"]],
                        "evidence": [{"path": selection_path.relative_to(root).as_posix(), "sha256": compiler.digest(selection_path)}, *req["evidence"], *generated_evidence]}]}
                if spec.get("working_source") is not None:
                    manifest["working_source"] = spec["working_source"]
                if req.get("hypothesis_binding") is not None:
                    manifest["candidates"][0]["hypothesis_binding"] = req["hypothesis_binding"]
                compiler.atomic(manifest_path, frontier.canonical(manifest) + b"\n")
                result["dispatched"] += 1
                measured = batch.run_batch(root=root, index=index, scratch=scratch, source_relpath=source_relpath,
                    object_relpath=object_relpath, compiler_script=compiler_script, manifest=manifest_path,
                    out=directory / "result.json", objdiff=objdiff, readelf=readelf, tools=tools,
                    workers=2, timeout=remaining())
                rows = measured.get("candidates", [])
                result["compiler_runs"] += sum(isinstance(row.get("compile_receipt"), dict) for row in rows)
                result["attempts"].append({"request": req["id"], "family": shape["family"],
                    "candidate_sha256": digest, "statuses": [r.get("status") for r in rows],
                    "result": evaluator._descriptor(directory / "result.json")})
                check()
                if measured.get("status") != "complete":
                    result.update(status="infrastructure_failed", reason=measured.get("reason", measured.get("status")))
                    return result
                gains = measured.get("ranked_admissible_gains", [])
                record = next((r for r in rows if gains and r.get("id") == gains[0].get("id")), None)
                # A prior still-bound gain must not become unreachable merely
                # because its source is now in the measured-source cache.
                if not record:
                    for cached in rows:
                        if cached.get("status") != "duplicate_source":
                            continue
                        descriptor = cached.get("reused_measurement", {}).get("result")
                        if not isinstance(descriptor, dict):
                            continue
                        cached_path, _ = _descriptor(root, descriptor)
                        cached_result = frontier.load_json(cached_path.read_bytes())
                        if (cached_result.get("status") in {"exact", "improved"}
                                and cached_result.get("baseline_index", {}).get("sha256") == result["baseline_index_sha256"]
                                and cached_result.get("candidate_source", {}).get("sha256") == digest
                                and cached_result.get("functions") == [req["function"]]):
                            record = {**cached, "evaluation": descriptor}
                            break
                if not record:
                    continue
                if not record or not isinstance(record.get("evaluation"), dict):
                    raise ValueError("gain has no bound evaluation result")
                measurement_path, _ = _descriptor(root, record["evaluation"])
                outcome = frontier.load_json(measurement_path.read_bytes())
                if outcome.get("status") not in {"exact", "improved"} or outcome.get("regressions") or outcome.get("review_required") or outcome.get("cleanup_errors"):
                    result["skipped"].append({"request": req["id"], "status": "gain_needs_source_or_data_review"})
                    continue
                result.update(status="measured_gain", winner=evaluator._descriptor(candidate_path), measurement=record["evaluation"])
                if "source_lineage" in selection:
                    result["source_lineage"] = selection["source_lineage"]
                if retain:
                    from tools import recovery_retain
                    lineage_kwargs = {"working_source": spec["working_source"]} if spec.get("working_source") is not None else {}
                    retained = recovery_retain.retain_gain(root=root, index=index, candidate=candidate_path,
                        functions=[req["function"]], measured_result=measurement_path, scratch=scratch,
                        source_relpath=source_relpath, object_relpath=object_relpath, compiler_script=compiler_script,
                        objdiff=objdiff, readelf=readelf, tools=tools or [], out_dir=directory / "retained",
                        timeout=remaining(), source_reviewed=True, **lineage_kwargs)
                    result["retention"] = retained
                    result["retained"] = retained.get("retained") is True
                    result["status"] = "retained_gain" if result["retained"] else retained.get("status", "retention_incomplete")
                return result
        return result
    except (OSError, ValueError, RuntimeError, TimeoutError) as exc:
        result.update(status="failed", reason=str(exc)[:2000])
        return result
    finally:
        result["seconds"] = time.monotonic() - started
        compiler.atomic(out_dir / "result.json", frontier.canonical(result) + b"\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("root", "index", "plan", "out-dir", "scratch", "compiler-script", "objdiff", "readelf"):
        parser.add_argument("--" + name, type=Path, required=True)
    for name in ("source-relpath", "object-relpath"):
        parser.add_argument("--" + name, required=True)
    parser.add_argument("--tool", type=Path, action="append", default=[])
    parser.add_argument("--max-candidates", type=int, default=8)
    parser.add_argument("--timeout", type=float, default=300)
    parser.add_argument("--retain", action="store_true")
    args = vars(parser.parse_args())
    args["tools"] = args.pop("tool")
    try:
        result = run(**args)
        print(json.dumps({k: result[k] for k in ("status", "generated", "compiler_runs", "retained")}))
        return 1 if result["status"] in {"failed", "infrastructure_failed"} else 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"guided recovery: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
