#ifndef DATANUM_FILESEL_H
#define DATANUM_FILESEL_H

#include "datadir_enum.h"

enum {
    FILESEL_HSF_BACKGROUND = DATANUM(DATA_filesel, 0),
    FILESEL_HSF_BOOK = DATANUM(DATA_filesel, 1),
    FILESEL_HSF_SIORI = DATANUM(DATA_filesel, 2),
    FILESEL_HSF_SIORI_MOJI = DATANUM(DATA_filesel, 3),
    FILESEL_HSF_DATA_SELECT = DATANUM(DATA_filesel, 4),
    FILESEL_DATA_05 = DATANUM(DATA_filesel, 5),
    FILESEL_ANM_06 = DATANUM(DATA_filesel, 6),
    FILESEL_ANM_07 = DATANUM(DATA_filesel, 7),
    FILESEL_ANM_08 = DATANUM(DATA_filesel, 8),
    FILESEL_ANM_09 = DATANUM(DATA_filesel, 9),
    FILESEL_ANM_10 = DATANUM(DATA_filesel, 10),
    FILESEL_ANM_11 = DATANUM(DATA_filesel, 11),
    FILESEL_ANM_12 = DATANUM(DATA_filesel, 12),
    FILESEL_ANM_13 = DATANUM(DATA_filesel, 13),
    FILESEL_ANM_14 = DATANUM(DATA_filesel, 14),
    FILESEL_ANM_15 = DATANUM(DATA_filesel, 15),
    FILESEL_ANM_16 = DATANUM(DATA_filesel, 16),
    FILESEL_ANM_17 = DATANUM(DATA_filesel, 17),
    FILESEL_ANM_18 = DATANUM(DATA_filesel, 18),
    FILESEL_ANM_19 = DATANUM(DATA_filesel, 19),
    FILESEL_DATA_20 = DATANUM(DATA_filesel, 20),
    FILESEL_DATA_21 = DATANUM(DATA_filesel, 21),
    FILESEL_DATA_22 = DATANUM(DATA_filesel, 22),
    FILESEL_DATA_23 = DATANUM(DATA_filesel, 23),
    FILESEL_HSF_OBJ1 = DATANUM(DATA_filesel, 24),
    FILESEL_ANM_25 = DATANUM(DATA_filesel, 25),
    FILESEL_HSF_SIORI_HIKARI = DATANUM(DATA_filesel, 26),
    FILESEL_HSF_SIORI_HIKARI2 = DATANUM(DATA_filesel, 27),
    FILESEL_DATA_28 = DATANUM(DATA_filesel, 28),
    FILESEL_ANM_DATA_SELECT = DATANUM(DATA_filesel, 29),
    FILESEL_DATA_30 = DATANUM(DATA_filesel, 30),
    FILESEL_DATA_31 = DATANUM(DATA_filesel, 31),
    FILESEL_DATA_32 = DATANUM(DATA_filesel, 32),
};

#endif
