#ifndef DATANUM_TITLE_H
#define DATANUM_TITLE_H

#include "datadir_enum.h"

enum {
    NINTENDO_SPRITE_DATA = DATANUM(DATA_title, 1),
    PROGRESSIVE_MSG_SPRITE_DATA = DATANUM(DATA_title, 6),
    PROGRESSIVE_ON_SPRITE_DATA = DATANUM(DATA_title, 7),
    PROGRESSIVE_OFF_SPRITE_DATA = DATANUM(DATA_title, 8),
    OPENING_WAIT_SPRITE_DATA = DATANUM(DATA_title, 9),
    PROGRESSIVE_CURSOR_SPRITE_DATA = DATANUM(DATA_title, 10),
    PROGRESSIVE_CURSOR_SEL_SPRITE_DATA = DATANUM(DATA_title, 11),
    TITLE_HSF_PARTY = DATANUM(DATA_title, 19),
    TITLE_HSF_STAR = DATANUM(DATA_title, 20),
    TITLE_HSF_SIX = DATANUM(DATA_title, 21),
};

#endif
